# I. NumPy.

**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

0. Імпортувати numpy загальноприйнятим способом.

In [ ]:
import numpy as np

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [1]:
import numpy as np
grades = [85, 90, 78, 92, 88, 76, 95]

grades_array = np.array(grades)
print("Одномірний масив оцінок:", grades_array)

Одномірний масив оцінок: [85 90 78 92 88 76 95]


2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [3]:
import numpy    as np
prices = [
    [10.5, 12.3, 8.9, 15.0],  # магазин 1
    [11.0, 12.0, 9.5, 14.8],  # магазин 2
    [10.8, 12.5, 9.0, 15.5]   # магазин 3
]

prices_matrix = np.array(prices)
print("Двовимірний масив цін:\n", prices_matrix)


Двовимірний масив цін:
 [[10.5 12.3  8.9 15. ]
 [11.  12.   9.5 14.8]
 [10.8 12.5  9.  15.5]]


3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [4]:

print("Тип даних масиву завдання 2:", grades_array.dtype)
print("Тип даних масиву завдання 3:", prices_matrix.dtype)


Тип даних масиву оцінок: int64
Тип даних масиву цін: float64


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [5]:

print("Форма масиву завдання 2:", grades_array.shape)
print("Форма масиву завдання 3:", prices_matrix.shape)


Форма масиву завдання 2: (7,)
Форма масиву завдання 3: (3, 4)


5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [6]:
profit = np.linspace(0, 1000.5, 7) 
print("Масив зростаючого прибутку за тиждень:", profit)


Масив зростаючого прибутку за тиждень: [   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [7]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

vertical_stack = np.vstack((array1, array2))
print("Вертикальне об'єднання:\n", vertical_stack)

horizontal_stack = np.hstack((array1, array2))
print("Горизонтальне об'єднання:", horizontal_stack)


Вертикальне об'єднання:
 [[1 2 3]
 [4 5 6]]
Горизонтальне об'єднання: [1 2 3 4 5 6]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [12]:
def transpose_array(array):
    """
    Функція транспонує вхідний одновимірний масив у вектор-стовпець за допомогою методу reshape.

    Parameters:
        array (numpy.ndarray): Одновимірний масив для транспонування.
                               Наприклад: [1, 2, 3].

    Returns:
        numpy.ndarray: Транспонований масив у вигляді вектора-стовпця.
                       Наприклад:
                       [[1],
                        [2],
                        [3]].
    """
    transposed = array.reshape(-1, 1)  # Перетворює у вектор-стовпець
    return transposed

example_array = np.array([7, 8, 9])
transposed_result = transpose_array(example_array)
print("Транспонований масив:\n", transposed_result)


Транспонований масив:
 [[7]
 [8]
 [9]]


8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [9]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

addition = array_a + array_b
print("Поелементне додавання:", addition)

subtraction = array_a - array_b
print("Поелементне віднімання:", subtraction)

multiplication_by_scalar = array_a * 2
print("Масив, помножений на 2:", multiplication_by_scalar)

elementwise_multiplication = array_a * array_b
print("Поелементне множення:", elementwise_multiplication)

matrix_multiplication = np.dot(array_a, array_b)
print("Матричне множення:", matrix_multiplication)


Поелементне додавання: [5 7 9]
Поелементне віднімання: [-3 -3 -3]
Масив, помножений на 2: [2 4 6]
Поелементне множення: [ 4 10 18]
Матричне множення: 32


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [13]:
import numpy as np

matrix = np.array([[3, 5, 7],
                   [2, 8, 6],
                   [9, 4, 1]])

min_value = matrix.min()

max_value = matrix.max()

sum_values = matrix.sum()

min_per_row = matrix.min(axis=1)

max_per_column = matrix.max(axis=0)

print("Мінімальне число:", min_value)
print("Максимальне число:", max_value)
print("Сума чисел:", sum_values)
print("Мінімальні числа для кожного рядка:", min_per_row)
print("Максимальні числа для кожного стовпчика:", max_per_column)


Мінімальне число: 1
Максимальне число: 9
Сума чисел: 45
Мінімальні числа для кожного рядка: [3 2 1]
Максимальні числа для кожного стовпчика: [9 8 7]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [14]:
matrix = np.array([[1, 2, 2],
                   [3, 1, 4],
                   [4, 2, 1]])

unique_values, counts = np.unique(matrix, return_counts=True)

print("Унікальні значення:", unique_values)
print("Частоти кожного значення:", counts)


Унікальні значення: [1 2 3 4]
Частоти кожного значення: [3 3 1 2]


# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [ ]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [18]:
import pandas as pd
data = {
    "Прізвище": ["Мокруха", "Мазафакер", "Броукб", "Свага"],
    "Ім'я": ["Тарас", "Олена", "Іван", "Едуард"],
    "Дата народження": ["1990-03-09", "1985-06-14", "2000-01-22", "2006-03-09"],
    "Маса тіла": [80, 65, None, 67], 
    "Медичне страхування": [True, False, True, True],
}

df = pd.DataFrame(data)

print("Датафрейм:\n", df)
print("\nТипи даних у кожній колонці:\n", df.dtypes)

Датафрейм:
     Прізвище    Ім'я Дата народження  Маса тіла  Медичне страхування
0    Мокруха   Тарас      1990-03-09       80.0                 True
1  Мазафакер   Олена      1985-06-14       65.0                False
2     Броукб    Іван      2000-01-22        NaN                 True
3      Свага  Едуард      2006-03-09       67.0                 True

Типи даних у кожній колонці:
 Прізвище                object
Ім'я                    object
Дата народження         object
Маса тіла              float64
Медичне страхування       bool
dtype: object


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [ ]:
import pandas as pd

file_path = "missile_attacks_daily.csv"  # Замініть на фактичний шлях до вашого файлу
data = pd.read_csv(file_path)
print("Дані успішно завантажені:")
print(data)


# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [3]:
import pandas as pd

file_path = "missile_attacks_daily.csv"
data = pd.read_csv(file_path)
print("Дані успішно завантажені:")
print(data)

print("Перші 10 рядків даних:")
print(data.head(10))


Дані успішно завантажені:
            time_start          time_end               model  \
0     2025-01-18 20:00  2025-01-19 09:00      Shahed-136/131   
1     2025-01-17 19:00  2025-01-18 08:00      Shahed-136/131   
2     2025-01-16 19:00  2025-01-17 09:00      Shahed-136/131   
3     2025-01-16 19:00  2025-01-17 09:00    Iskander-M/KN-23   
4     2025-01-16 19:00  2025-01-17 09:00          Iskander-M   
...                ...               ...                 ...   
2039  2022-10-01 12:00  2022-10-01 12:00            Orlan-10   
2040        2022-09-30        2022-09-30            Orlan-10   
2041  2022-09-29 23:00  2022-09-29 23:59      Shahed-136/131   
2042        2022-09-28        2022-09-28                X-59   
2043        2022-09-28        2022-09-28  Reconnaissance UAV   

                                           launch_place  \
0         Bryansk oblast and Oryol oblast and Millerovo   
1     Primorsko-Akhtarsk and Bryansk oblast and Mill...   
2     Primorsko-Akhtarsk and

14. Отримайте інформацію про форму датафрейму.

In [4]:
print("Форма датафрейму (рядки, стовпці):")
print(data.shape)


Форма датафрейму (рядки, стовпці):
(2044, 16)


15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [5]:
print("Інформація про кожну колонку:")
print(data.info())


Інформація про кожну колонку:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2044 entries, 0 to 2043
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2044 non-null   object 
 1   time_end              2044 non-null   object 
 2   model                 2044 non-null   object 
 3   launch_place          1023 non-null   object 
 4   target                2016 non-null   object 
 5   carrier               225 non-null    object 
 6   launched              2041 non-null   float64
 7   destroyed             2044 non-null   int64  
 8   not_reach_goal        157 non-null    float64
 9   cross_border_belarus  32 non-null     float64
 10  back_russia           34 non-null     float64
 11  still_attacking       28 non-null     float64
 12  destroyed_details     294 non-null    object 
 13  launched_details      4 non-null      object 
 14  launch_place_details  4 non-null      obje

16. Отримайте статистику для колонок числового типу.

In [6]:
print("Статистика для числових колонок:")
print(data.describe())


Статистика для числових колонок:
          launched    destroyed  not_reach_goal  cross_border_belarus  \
count  2041.000000  2044.000000      157.000000             32.000000   
mean     10.609995     7.491683       20.828025              2.312500   
std      21.041038    14.190972       19.877245              2.054696   
min       1.000000     0.000000        1.000000              1.000000   
25%       1.000000     1.000000        4.000000              1.000000   
50%       2.000000     1.000000       16.000000              2.000000   
75%       9.000000     7.000000       30.000000              2.000000   
max     193.000000    99.000000      105.000000             10.000000   

       back_russia  still_attacking  
count    34.000000        28.000000  
mean      2.000000         2.821429  
std       1.154701         2.931989  
min       1.000000         1.000000  
25%       1.000000         1.000000  
50%       2.000000         1.000000  
75%       3.000000         4.000000  
max  

17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [7]:
unique_values = data.nunique()
print("Кількість унікальних значень у кожній колонці:")
print(unique_values)

min_unique_column = unique_values.idxmin()
min_unique_count = unique_values.min()
print(f"Колонка з найменшою кількістю унікальних значень: '{min_unique_column}' ({min_unique_count} значень)")

Кількість унікальних значень у кожній колонці:
time_start               864
time_end                1015
model                     61
launch_place             135
target                    97
carrier                   58
launched                 113
destroyed                 81
not_reach_goal            55
cross_border_belarus       7
back_russia                5
still_attacking            8
destroyed_details        290
launched_details           4
launch_place_details       4
source                   960
dtype: int64
Колонка з найменшою кількістю унікальних значень: 'launched_details' (4 значень)


18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

**місце для текстової відповіді**

1.   Перевірити наявність пропущених значень у колонках
2.   Перевірити коректність типів даних у кожній колонці

...


# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [8]:
if 'launched' in data.columns:
    try:
        data['launched'] = pd.to_numeric(data['launched'], errors='coerce').astype('Int64')
        print("Колонка 'launched' успішно перетворена у тип Int64.")
    except Exception as e:
        print(f"Помилка під час перетворення: {e}")
else:
    print("Колонка 'launched' відсутня у датасеті.")

print(data['launched'].dtypes)


Колонка 'launched' успішно перетворена у тип Int64.
Int64


20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [9]:
threshold = 0.3 
min_non_nulls = len(data) * threshold
filtered_data = data.dropna(thresh=min_non_nulls, axis=1)

print("Колонки збережені після фільтрації:")
print(filtered_data.columns)

removed_columns = set(data.columns) - set(filtered_data.columns)
print(f"Видалено колонок: {len(removed_columns)}")


Колонки збережені після фільтрації:
Index(['time_start', 'time_end', 'model', 'launch_place', 'target', 'launched',
       'destroyed', 'source'],
      dtype='object')
Видалено колонок: 8


21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

In [ ]:

initial_rows = len(data)

data_cleaned = data.drop_duplicates()

column_to_filter = 'destroyed'
if column_to_filter in data_cleaned.columns:
    data_cleaned = data_cleaned[data_cleaned[column_to_filter] > 0]


data_cleaned.reset_index(drop=True, inplace=True)

removed_rows = initial_rows - len(data_cleaned)
print(f"Видалено рядків: {removed_rows}")


Видалено рядків: 433


**місце для текстової відповіді**

In [ ]:
було видалено 433 рядка, видалення рядків враховується завдяки порівнянню початкової кількості рядків із кінцевою кількістю рядків після виконання операцій очищення даних.

22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [10]:
rows_with_na = data[data.isnull().any(axis=1)]
print("Рядки з хоча б одним пропущеним значенням:")
print(rows_with_na)

print(f"Кількість рядків з пропущеними значеннями: {len(rows_with_na)}")


Рядки з хоча б одним пропущеним значенням:
            time_start          time_end               model  \
0     2025-01-18 20:00  2025-01-19 09:00      Shahed-136/131   
1     2025-01-17 19:00  2025-01-18 08:00      Shahed-136/131   
2     2025-01-16 19:00  2025-01-17 09:00      Shahed-136/131   
3     2025-01-16 19:00  2025-01-17 09:00    Iskander-M/KN-23   
4     2025-01-16 19:00  2025-01-17 09:00          Iskander-M   
...                ...               ...                 ...   
2039  2022-10-01 12:00  2022-10-01 12:00            Orlan-10   
2040        2022-09-30        2022-09-30            Orlan-10   
2041  2022-09-29 23:00  2022-09-29 23:59      Shahed-136/131   
2042        2022-09-28        2022-09-28                X-59   
2043        2022-09-28        2022-09-28  Reconnaissance UAV   

                                           launch_place  \
0         Bryansk oblast and Oryol oblast and Millerovo   
1     Primorsko-Akhtarsk and Bryansk oblast and Mill...   
2     Primo